# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_card.ipynb.

# %% auto 0
__all__ = ['Booger']

# %% ../nbs/01_card.ipynb 4
class Booger:
    "A Booger object"
    def __init__(self, 
                 snots:int, # A snot is the individual component of a booger. A booger can have multiple snots
                 phlegm:bool # Phlegm is the quality of a booger ie wetness
                ): self.snots,self.phlegm= snots,phlegm
    def __str__(self): 
        if self.phlegm:
            wet= "it is wet"
        else:
            wet= "it isn't wet"
        return f"{self.snots}# of snots in this Booger and {wet} "
    __repr__=__str__

